# Generated by Django 4.1.3 on 2022-11-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "address",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("status", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "appointment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.DecimalField(decimal_places=0, max_digits=10)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=20)),
                ("license_no", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "doctor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_of_expertise", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "expertise",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LaboratoryTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "laboratory_test",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "medication",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("phone_number", models.DecimalField(decimal_places=0, max_digits=10)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "patient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "time_slot",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("visit_date", models.DateField()),
                ("visit_time", models.TimeField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "visit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VisitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "visit_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                ("ward_number", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "number_of_beds",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ward",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Admits",
            fields=[
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="records.visit",
                    ),
                ),
                ("admit_date", models.DateField()),
                ("admit_time", models.TimeField()),
                ("discharge_date", models.DateField(blank=True, null=True)),
                ("discharge_time", models.TimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "admits",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExpertIn",
            fields=[
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="records.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "expert_in",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PerformsLabTest",
            fields=[
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="records.visit",
                    ),
                ),
                ("perform_by_date", models.DateField()),
                (
                    "test_results",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("performed_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "performs_lab_test",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Prescribes",
            fields=[
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="records.visit",
                    ),
                ),
                ("daily_dose", models.CharField(max_length=50)),
                (
                    "number_of_days",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prescribes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WorksOn",
            fields=[
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="records.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "works_on",
                "managed": False,
            },
        ),
    ]
